CREATE TABLE dbo.Carro (
	ID INT PRIMARY KEY IDENTITY (1, 1),
	Marca VARCHAR(200) NOT NULL,
	Modelo VARCHAR(200) NOT NULL,
	Versao VARCHAR(200) NOT NULL,
	Ano INT NOT NULL,
	Quilometragem INT NULL,
	Observacao VARCHAR(500) NULL 
);
GO

CREATE TABLE dbo.Council (
	ID INT PRIMARY KEY IDENTITY (1, 1),
	DistrictID INT FOREIGN KEY REFERENCES dbo.District(ID) NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	Active BIT NOT NULL DEFAULT 1
);
GO